### ISSUE TITLE
SYN053+1.mg makes maetning hang unexpectedly.

### ISSUE THREAD

**Issue by tausbn** [chaudhuri/maetning#3]

**Comment by chaudhuri** [comment]
The issue here is that percolation is spinning with copies of existing rules. I got the loops backwards. It is for every active for every rule, not for every rule for every active.

Ultimately this should be fixed with rule subsumption, but it's kind of hard to implement it.

**Comment by chaudhuri** [comment]
This is no longer problematic, but I forgot to note down what fixed it. Maybe d4a853283a66b1 ?
